### ISSUE TITLE
MySQL can't find openssl

### ISSUE THREAD

**Issue by Ulrar** [rumpkernel/rumprun-packages#137] opened 2017-03-27 19:47 UTC
Hi,

I've been trying to compile the mysql package, but I get this : 

```
CMake Error at cmake/ssl.cmake:167 (FILE):
  file STRINGS file
  "/home/username/workspace/rumprun-packages/mysql/build/mysql/OPENSSL_INCLUDE_DIR-NOTFOUND/openssl/opensslv.h"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:419 (MYSQL_CHECK_SSL)


-- OPENSSL_INCLUDE_DIR = OPENSSL_INCLUDE_DIR-NOTFOUND
-- OPENSSL_LIBRARY = OPENSSL_LIBRARY-NOTFOUND
-- CRYPTO_LIBRARY = CRYPTO_LIBRARY-NOTFOUND
-- OPENSSL_MAJOR_VERSION = 
CMake Error at cmake/ssl.cmake:247 (MESSAGE):
  Cannot find appropriate system libraries for SSL.  Make sure you've
  specified a supported SSL version.  Consult the documentation for WITH_SSL
  alternatives
Call Stack (most recent call first):
  CMakeLists.txt:419 (MYSQL_CHECK_SSL)
```

As I understand it it's supposed to use the bundled version, so my system has nothing to do with it right ? I guess it might be a difference in my cmake version, I'm running 3.6.3 on Gentoo.

**Comment by anttikantee** [comment] 2017-03-27 20:12
duplicate of #106

**Closed as completed by anttikantee** 2017-03-27 20:12 UTC
